### PR TITLE
some improvements (?) to the english and promotional tone (marketing) of...

### PR DESCRIPTION
**Pull request by robjens**
... the framework...cherry pick them as you please

While evaluating total.js for a project of ours / experimenting, I found some issues I thought could be improved in the english. I took some liberty here and there, you may not like all of them (heck I might not even) so include/exclude as you please - I won't be offended ;)

I'll probably turn in a Dutch translation if you like sometime, that is to also say I'm not a native English speaker but I'm sure after me someone will come around some time and fix my errors :)

Cheers

### CODE REVIEW

**Comment by robjens** [comment]
p.s. I don't think the project names `website

**Comment by petersirka** [comment]
Thanks @robjens. I appreciate it. I will think about your thought :+1:

**Comment by petersirka** [comment]
Do you know to translate the website to __Dutch__?
If no, I won't be offended :100:

**Comment by robjens** [comment]
@petersirka I'll get to it as soon as I have a spare hour. I have to deliver a Clojure Hoplon project involving webdriver, gmail and calendar first... luckily I have about most libraries figured out now, not much till monday :D

**Comment by petersirka** [comment]
Good luck and thanks.

**Comment by petersirka** [comment]
@robjens I found a big design problem, could you update it? If you will have a free time? You don't to have a fork, just download <https://github.com/totaljs/website/archive/master.zip> and send me updated `en.resource`. 10000x thanks!

English

**Comment by robjens** [comment]
Ok I'll take a look in a bit. In the mean time, could you perhaps elaborate a bit more on some 'vague' wordings? Some places in the text you make categorical statements, only to provide e.g. a single example. It would help if you could summarize a few cases of such statements/features as to further promote the attribute/distinguished feature a bit more:

- Define a different actions to one url and distribute by e.g. HTTP methods **(which other ones?)**. The framework contains very good routing. **(reworded already)**, but elaborate - _what_ makes it qualify as 'very good' - say, excellent routing?

-  Perfect security **(very dangerous statement)** Explain more what makes it rock solid: request and data encoding is very, very broad.

- Automation ... You don't need other tools (e.g. Grunt). **(really? really?)** if so, provide more examples of what Grunt does that we can do - minimization alone is not enough to convince someone who's been using Grunt for a fair deal of their work/build flow)

-  Ready to enterprise: The framework has a good architecture for big applications **(why? how?)** and on the one project can work more developers. **(how? does it have collaborative functionality?)**

I'm sure there are a few more but then again, those small 'tiles' on the web site may become full blown links to more extensive documentation later.

I'm guessing your layout problems have something to do with that :P

I'll have look later but wanted to post/ask this yesterday already and I'm no less in a rush... so this may get done tomorrow instead ;)

**Comment by petersirka** [comment]
@robjens thanks for your advice. I'll analyze your text detailed. We can attack on the each word but I aggree with you. Thanks again.

**Pull request merged**
